<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260916135206 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE adherent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_j VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, date_naiss_j TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, categorie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90D3F060BCF5E72D ON adherent (categorie_id)');
        $this->addSql('ALTER TABLE adherent ADD CONSTRAINT FK_90D3F060BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE adherent DROP CONSTRAINT FK_90D3F060BCF5E72D');
        $this->addSql('DROP TABLE adherent');
    }
}
