<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260923122250 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE obtenir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention DATE NOT NULL, id_c_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED792AC91AF787D1 ON obtenir (id_c_id)');
        $this->addSql('ALTER TABLE obtenir ADD CONSTRAINT FK_ED792AC91AF787D1 FOREIGN KEY (id_c_id) REFERENCES ceinture (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE obtenir DROP CONSTRAINT FK_ED792AC91AF787D1');
        $this->addSql('DROP TABLE obtenir');
    }
}
